### ISSUE TITLE
Suppress warnings for invalid user agent

### ISSUE THREAD

**Issue by miike** [snowplow/stream-collector#178]
Currently Akka raises warnings where the User-Agent is considered to have invalid input. There are a large number of useragents including Facebook, bots and just regular useragents that contain these symbols (e.g., [, ], ;, etc) so this can result in a large number of warnings raised in the logs (Cloudwatch / Cloud Monitoring).

In addition - due to the way these errors are raised with newlines this yields two rows (one which is just ^). For higher volumes pipelines this can easily result in tens to hundreds of million warnings per day which accumulate associated costs in terms of network egress / log storage.

As this is a warning these useragents can be processed / enriched without any issue in the Snowplow pipeline so removing them does not cause any side effects.

```
[WARN] [10/08/2021 14:53:36.375] [scala-stream-collector-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(scala-stream-collector)] Illegal header: Illegal 'user-agent' header: Invalid input '[', expected 'EOI', product-or-comment, WSP, comment, CRLF or ws (line 1, column 6): YEET [123]
     ^
```

**Comment by istreeter** [comment]
Hey @miike I'm starting to think we should prevent logging of all invalid headers, not just user-agent.  Meaning I suggest we set:

```
akka.http.parsing.illegal-header-warnings=off
```

My reasons are:

* All headers are valid from Snowplow's point of view, so need to log warnings.
* The last few days have made us paranoid about logging user data (log4shell etc)
* More generally, for PII reasons we should remove logging of user-sent fields from everywhere in the Snowplow pipeline.  Log files are easier to manage and share if we can guarantee there is no user data whatsoever.  Headers are admittedly mostly harmless, but we shouldn't make an exception.
* I can't think of any reason someone would want to see these warning messages.
* Users can override our decision if they disagree, by setting `akka.http.parsing.illegal-header-warnings=on` in their config file
