### ISSUE TITLE
PubSub: make it possible to use PubSub emulator

### ISSUE THREAD

**Issue by benjben** [snowplow/stream-collector#270]
Similarly to AWS with `localstack`, Google provides a [Pub/Sub emulator](https://cloud.google.com/pubsub/docs/emulator) for local tests.

Using it is normally as simple as [running the Docker image](https://cloud.google.com/sdk/docs/downloads-docker) and [setting `PUBSUB_EMULATOR_HOST`](https://cloud.google.com/pubsub/docs/emulator#manually_setting_the_variables).

But [not for Java/Scala](https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables) : 

```
In all languages except for Java and C#, if you have set PUBSUB_EMULATOR_HOST as described in [Setting environment variables](https://cloud.google.com/pubsub/docs/emulator#env), the Pub/Sub client libraries automatically call the API running in the local instance rather than Pub/Sub.

However, C# and Java client libraries require you to modify your code to use the emulator.
```

We need to add code that modifies the behavior if `PUBSUB_EMULATOR_HOST` is set.

**Comment by dakl** [comment]
What's the status of this one? I'd love to see it happen :)

**Comment by benjben** [comment]
Hi @dakl , it's been [merged](https://github.com/snowplow/stream-collector/commit/f652a592ac15ea013526a7fc9cf364d6e1ebf85d) to `develop` already and it will be released probably the week after next week (it will be announced on [discourse](https://discourse.snowplow.io/)). But you can start using it already with `2.8.3-rc5`.
