### ISSUE TITLE
Ensure integration tests expect tags like x.x.x-distroless

### ISSUE THREAD

**Issue by lmath** [snowplow/stream-collector#298]
In https://github.com/snowplow/stream-collector/pull/297

I updated the tag in the docker distroless settings for distroless images to be of format x.x.x-distroless [here](https://github.com/snowplow/stream-collector/pull/297/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R89) but I did not realise that the integration tests were using distroless images but expecting x.x.x and the test broke when I merged https://github.com/snowplow/stream-collector/pull/297 into develop. So we should make sure that the integration tests expect a tag like x.x.x-distroless.

**Comment by istreeter** [comment]
Closing this issue because we're going to squash the fix into the previous commit when we release it.
