### ISSUE TITLE
Stream Collector: add stdout artifact

### ISSUE THREAD

**Issue by tgampiyush** [snowplow/stream-collector#3]
**Project**: Scala Stream Collector - stdout

**Version**: 1.0.0

**Expected behavior**: The jar should be created with name - snowplow-stream-collector-stdout-{$versionn-no}.jar 

**Actual behavior**: The project just clean and compile and no jar is created

**Steps to reproduce**:
 sbt "project stdout" assembly

 1. Just try to create an assembly for scala stream collector module where the output set to stdout  - 
using the command - 
 sbt "project stdout" assembly

**PR already create to resolve it -**
https://github.com/snowplow/snowplow/pull/4278

**Comment by dilyand** [comment]
Closed in: https://github.com/snowplow/stream-collector/commit/74311bb20df1d713f7071d0cb51100c951b5108a
