### ISSUE TITLE
Run background check for Kinesis if it is made unhealthy and SQS buffer is activated

### ISSUE THREAD

**Issue by dkbrkjni** [snowplow/stream-collector#315]
If the collector fails to push events to Kinesis enough times that it exceeds the [maxRetries](https://github.com/snowplow/stream-collector/blob/d9ee3850b5a3625bd6a751af0f93a552802d6e27/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L64), it will mark the Kinesis stream as [unhealthy](https://github.com/snowplow/stream-collector/blob/d9ee3850b5a3625bd6a751af0f93a552802d6e27/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L216). Once this happens the Collecter will newer update `kinesisHealthy` state, and forever push all events into the SQS Buffer.

**Comment by benjben** [comment]
It is made healthy again on [this line](https://github.com/snowplow/stream-collector/blob/2.9.0/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L154) or [this line](https://github.com/snowplow/stream-collector/blob/2.9.0/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L365)

**Comment by benjben** [comment]
It seems that there is a problem indeed, the background check for Kinesis is called [only once at startup](https://github.com/snowplow/stream-collector/blob/2.9.0/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L454) but is not called again when Kinesis sink is made unhealthy. It should be called [here](https://github.com/snowplow/stream-collector/blob/2.9.0/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L365).
