### ISSUE TITLE
Send too big events (for Kinesis/Sqs) as a bad row.

### ISSUE THREAD

**Issue by lukeindykiewicz** [snowplow/stream-collector#54]

**Comment by dilyand** [comment]
This is not referring to a `sizeViolation` bad row, which had already been introduced here: https://github.com/snowplow/snowplow/issues/4177.

This is referring to events that have been sent to SQS via the surge protection buffer but are too big to fit in there.

This is not actually an issue -- the solution is using the proper `MaxBytes` setting, along the lines of what is said in the linked discussion.

Closing.
